---
#
# Setup/update homebrew junk
#
- hosts: localhost
  vars:
    - git_netrc_src: "/share/git-core/contrib/credential/netrc/git-credential-netrc"
    - git_netrc_dst: "/libexec/git-core/git-credential-netrc"
  # Make shit happen!
  tasks:
    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Upgrade Homebrew installs
      homebrew: upgrade_all=yes

    - name: Get brew install location
      shell: >-
        brew config |
        grep HOMEBREW_PREFIX |
        awk -F': ' '{print $2}'
      register: brew_home

    - name: Setup Homebrew taps
      homebrew_tap: name={{item}} state=present
      with_items:
        - homebrew/dupes
        - homebrew/science
        - homebrew/versions
        - mpv-player/mpv
        - mitchty/yuck
        - mitchty/clang_scan_view
        - mitchty/clang_scan_build

    - name: Install tmux
      homebrew: state=present name=tmux install_options=wrap-pbcopy-and-pbpaste

    - name: Make tmux copy/paste with osx possible
      homebrew: state=present name=reattach-to-user-namespace

    - name: Install mosh from HEAD
      homebrew: state=head name=mobile-shell

    - name: Install basic tools
      homebrew: name={{item}} state=present
      with_items:
        - gpg
        - git
        - ansible
        - htop

    # Ok so we need to setup the gpg credential helper for netrc
    - name: Get installed brew git version
      shell: >-
        brew info git 2>&1 |
        head -n 1 |
        awk '{print $3}' |
        sed -e 's/,//g'
      ignore_errors: true
      register: brew_git_version

    - name: Create link for git-credential-netrc to work
      file: >-
        src="{{brew_home.stdout}}/Cellar/git/{{brew_git_version.stdout}}{{git_netrc_src}}"
        dest="{{brew_home.stdout}}/Cellar/git/{{brew_git_version.stdout}}{{git_netrc_dst}}"
        state=link

    - name: Install emacs with cocoa/srgb options
      homebrew: state=present name=emacs install_options=cocoa,srgb

    - name: Install curl with openssl/async dns options
      homebrew: state=present name=curl install_options=with-openssl,with-ares

    - name: Install stuff that I might want to use more quickly
      homebrew: name={{item}} state=present
      with_items:
        - youtube-dl
        - irssi
        - ag
        - ispell
        - docbook
        - asciidoc
        - libxml2
        - libxslt
        - readline
        - sqlite
        - gdbm

    - name: Install python with universal/framework options
      homebrew: state=present name=python install_options=universal,framework

    # all this because 10.9 doesn't include libxml2 in the platform
    # headers, LAME, also grr
    - name: Get libxml2 pkg path
      shell: >-
        brew --env libxml2 |
        grep PKG_CONFIG_PATH |
        awk -F'=' '{print $2}' |
        sed -e 's/\"//g'
      register: libxml_pkg_config_path

    - name: Get libxml2 pkg libdir
      shell: >-
        brew --env libxml2 |
        grep PKG_CONFIG_LIBDIR |
        awk -F'=' '{print $2}' |
        sed -e 's/\"//g'
      register: libxml_pkg_config_libdir

    - name: Get libxml2 CFLAGS
      environment:
        PKG_CONFIG_PATH: "{{libxml_pkg_config_path.stdout}}"
        PKG_CONFIG_LIBDIR: "{{libxml_pkg_config_libdir.stdout}}"
      command: pkg-config --cflags libxml-2.0
      register: libxml_cflags

    - name: Get libxml2 LIBS
      environment:
        PKG_CONFIG_PATH: "{{libxml_pkg_config_path.stdout}}"
        PKG_CONFIG_LIBDIR: "{{libxml_pkg_config_libdir.stdout}}"
      command: pkg-config --libs libxml-2.0
      register: libxml_libs

    - name: Install Python pip modules
      environment:
        CFLAGS: "{{libxml_cflags.stdout}}"
        LIBS: "{{libxml_libs}}.stdout"
        PKG_CONFIG_PATH: "{{libxml_pkg_config_path.stdout}}"
        PKG_CONFIG_LIBDIR: "{{libxml_pkg_config_libdir.stdout}}"
        XML_CATALOG_FILES: "{{brew_home}}/etc/xml/catalog"
        DYLD_LIBRARY_PATH: "{{brew_home}}/lib"
      shell: >-
        "{{brew_home.stdout}}/bin/pip" install --upgrade
        docutils
        howdoi
        pep8
        pyflakes
        flake8

    - name: Install ruby
      homebrew: state=present name=ruby

    - name: Install/Upgrade ruby gems
      shell: >-
        "{{brew_home.stdout}}/bin/gem" install --no-ri --no-rdoc
        pry maid jist

    - name: Install perl
      homebrew: state=present name=perl

    - name: Get hombrew perl /bin directory
      command: brew --prefix perl
      register: brew_perl_bin

    - name: Install cpanminus
      shell: >-
        curl -kL http://cpanmin.us |
        "{{brew_perl_bin.stdout}}/bin/perl" - App::cpanminus

    - name: Install/Update cpan modules
      shell: >-
        "{{brew_perl_bin.stdout}}/bin/cpanm"
        App::cpanminus
        App::rainbarf
        Perl::Tidy
        Perl::Critic
        Encode
        Storable
        List::Util
        Hash::Util
        IO::Socket

    - name: Install postgres without perl/tcl/python options
      homebrew: state=present name=postgres install_options=no-perl,no-tcl,without-python
    - name: Install mpv movie player with with-bundle option
      homebrew: state=present name=mpv install_options=with-bundle

    - name: Install the rest of the lot
      homebrew: name={{item}} state=present
      with_items:
        - keychain
        - yuck
        - openssl
        - pigz
        - xz
        - pixz
        - pbzip2
        - pv
        - iperf
        - nmap
        - sntop
        - rsync
        - entr
        - iftop
        - tree
        - pngcrush
        - wget
        - mercurial
        - ack
        - ncurses
        - go
        - python3
        - clang-scan-view
        - clang-scan-build
        - gcc
        - llvm

    - name: brew cleanup
      command: brew cleanup
