;;-*-mode: emacs-lisp; coding: utf-8;-*-
(add-to-list 'load-path "~/.emacs.d/shm/elisp")
(require 'haskell-mode)
(require 'haskell-process)
(require 'haskell-simple-indent)
(require 'haskell-interactive-mode)
(require 'haskell-font-lock)
(require 'haskell-debug)
(require 'sgml-mode)
(require 'css-mode)
(require 'shm)
(require 'helm-config)
(helm-mode 1)
(color-theme-solarized-light)
(set-face-background 'shm-current-face "#eee8d5")
(set-face-background 'shm-quarantine-face "lemonchiffon")
