;;-*-mode: emacs-lisp; coding: utf-8;-*-
(auto-complete-mode)
(whitespace-mode)
(hl-line-mode)
(smartparens-mode)
(diff-hl-mode)
(fixmee-mode)
(visual-line-mode)
(setq indent-tabs-mode nil)
(setq tab-width 2)
