#!/usr/bin/env sh
#-*-mode: Shell-script; coding: utf-8;-*-

type emacs > /dev/null 2>&1
if [[ $? == 0 ]]; then
  function ee
  {
    . ${HOME}/src/orb/orb.sh
    opl use emacs
    orb use emacs
  }

  function se
  {
    (
      ee
      emacs --daemon
    )
  }

  function qe
  {
    emacsclient -t -e "(save-buffers-kill-emacs) (shutdown-emacs-server)"
  }

  function te
  {
    emacsclient -t -e "(menu-bar-mode -1)" > /dev/null 2> &1
    if [[ $? != 0 ]]; then
      se
      emacsclient -t -e "(menu-bar-mode -1)"
    fi
  }

  function oe
  {
    emacsclient -n -c -e "(tool-bar-mode -1) (menu-bar-mode 1)" > /dev/null > 2>&1
    if [[ $? != 0 ]]; then
      se
      emacsclient -n -c -e "(tool-bar-mode -1) (menu-bar-mode 1)"
    fi
  }
fi
