#!/usr/bin/env sh
#-*-mode: Shell-script; coding: utf-8;-*-

function go_hook {
  # Setup GOPATH as appropriate.
  if [[ $(which go) != '' ]]; then
    gopath=${HOME}/.go
    [[ ! -d ${gopath} ]] && mkdir -p ${gopath}/bin
    export GOPATH=${gopath}
    pushem ${GOPATH}
  fi
}

_push_hook "go_hook"
