#!/usr/bin/env sh
#-*-mode: Shell-script; coding: utf-8;-*-
# Makes sure all is sourced in the proper order and sets up anything needed.
#
# The way I'm setting this up is that prefix needs to be set prior to getting
# sourced, otherwise this house of cards doesn't work.
#
# Order of sourcing is mostly boring.
#
# * First, sources basic files stored in ${HOME}/src TODO: find a way for ksh
#   to know where sourcing so I can remove this hardcoded nonsense
# * Then sources things in ${HOME}/site/local files (basically site dirs look like src/funcs)
#
# This allows site specific customization while keeping defaults simple.
#
# Other peculiarities include os-specific related setup.
#
# os-foo for example would get sourced after all those are sourced and we are
# running on a foo system (uname -s basically)
#
# After the generic os- is sourced, then the vendortype is sourced. This is so I
# can have Linux specific stuff in one place, then rhel/suse/arch/whatever
# separated.
#
# host-bar would get sourced if the current host's name is bar.

# Setup stuff needed for hooks
_post_hooks=''

function _push_hook {
  if [[ ${_post_hooks} == '' ]]; then
    _post_hooks="$*"
  else
    _post_hooks="${_post_hooks}:$*"
  fi
}

if [[ ${prefix:+1} == 1 ]]; then
  # HACK for TERM (a)buse, some profiles set TERM unconditionally.
  # keep what we get from ssh
  ORIG_TERM=${TERM}

  set -A load_order ${prefix}/gits/github.com/mitchty/src/funcs ${prefix}/site/local

  # load defaults, then site/local
  for load_prefix in ${load_order[*]}; do
    [[ ! -d ${load_prefix} ]] && break

    # load the bare files in load_prefix next
    for file in $(ls -d ${load_prefix}/* | grep -v sourceme); do
      [[ -f ${file} ]] && . ${file}
    done

    # TODO: Make this go somewhere else, total hack for now.
    echo $PATH | grep ${prefix}/gits/github.com/mitchty/src > /dev/null 2>&1
    [[ $? != 0 ]] && unshiftem "${prefix}/src"

    # Add in the bin dir if it exists to PATH
    [[ -d ${load_prefix}/bin ]] && unshiftem ${load_prefix}

    # load os flavor/vendor files (sourced in with os for most funcs)
    # so for things like osx I can get homebrew stuff sourced for the rest
    flavor="${load_prefix}/oses/$(os_uname_s)"
    if [[ -f ${flavor} ]]; then
      . ${flavor}
    else
      echo '\e[91mWarning, unix flavor file not found@'${flavor}'\e[0m'
    fi

    # aka, linux is a type of os, suse/redhat are a vendor of that os
    # miniscule distinction but meh, it helps somewhat
    vendor="${load_prefix}/oses/$(os_type)"
    if [[ -f ${vendor} ]]; then
      . ${vendor}
    else
      echo '\e[91mWarning, unix vendor file not found@'${vendor}'\e[0m'
    fi

    # And any host specific stuff (should only be in site/local if at all)
    hostname=$(host_name)
    hostnamefile="${load_prefix}/hosts/$(host_name)"
    [[ -f ${hostnamefile} ]] && source ${hostnamefile}

    # Ok so run through the hook functions in LIFO order.
    # Quick hack to deal with PATH on OSX not always having ~/homebrew/bin when files
    # are sourced. Since I want things to be idempotent, functions defining functions
    # and called at the end as a LIFO buffer makes this possible without much
    # change

    for hook in $(echo $_post_hooks | sed -e 's/:/ /g'); do
      ${hook}
    done

    _post_hooks=''
  done

  alias_setup
  stty -ixon
else
  echo "\e[91m\${prefix} not set. Refusing to do anything."
fi
